import { writable } from 'svelte/store';
export const userEmail = writable("");
export const refereeOfClub = writable(false);
export const refereeOfCounty = writable(false);
export const secretaryOfClub = writable(false);
export const secretaryOfCounty = writable(false);
export const secretaryOfProvince = writable(false);
export const secretaryOfCouncil = writable(false);
export const teamOfficial = writable(false);
export const firstName = writable("");
export const lastName = writable("");
export const clubRef = writable("");
export const teams = writable([]);
export const games = writable([]);
export const clubCrest = writable("");
export const countyCrest = writable("");
export const clubName = writable("");
export const countyName = writable("");
export const provinceName = writable("");


export const resetStore = () => {
    userEmail.set("");
    refereeOfClub.set(false);
    refereeOfCounty.set(false);
    secretaryOfClub.set(false);
    secretaryOfCounty.set(false);
    secretaryOfProvince.set(false);
    secretaryOfCouncil.set(false);
    teamOfficial.set(false);
    firstName.set("");
    lastName.set("");
    clubRef.set("");
    teams.set([]);
    games.set([]);
    clubCrest.set("");
    countyCrest.set("");
    clubName.set("");
    countyName.set("");
    provinceName.set("");
    console.log("Store Reset");
};